title: Chai
description: |
  Chai 是一个针对 [node](http://nodejs.org) 和浏览器的行为驱动开发/测试驱动开发断言库，可以自由的搭配任何javascript测试框架。
baseurl: ""

safe: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: js

exclude:
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md

googleanalytics: "UA-26183904-6"
mixpanel: "d5e84615dbd02dbc359b0f76d0ed7cf5"
tweeturl: "http://chaijs.com"
tweetvia: "jakeluer"
tweetrelated: "jakeluer"
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: guide
      type: guides
    values:
      layout: guide
      bodyClass: guide
      weight: 0
  -
    scope:
      path: api
    values:
      layout: api
      bodyClass: api

collections:
  guides:
      output: true
      permalink: /guide/:path/
      bodyClass: guide

featuredplugin:
  name: chai-webdriver
  url: /plugins/chai-webdriver
  blurb: |
    Create expressive integration tests with chai and
    [selenium-webdriver](https://npmjs.org/package/selenium-webdriver).
  example: |
    chai.use(chaiWebdriver(driver));
    driver.get('http://chaijs.com/');
    expect('nav h1').dom.to.contain.text('Chai');
    expect('#node .button').dom.to.have.style('float', 'left');
